### PR TITLE
Add contrib/plugins

### PR DESCRIPTION
**Pull request by morallo**
Solves #5

### CODE REVIEW

**Comment by blacktop** [comment]
I really appreciate you pointing this out, but I think it makes more sense to add the community plugins to the main plugin folder instead of the other way around?  That way you don't have to even add the --plugin flag?  Is there a way for you to test a community plugin from the last push I did?

**Comment by morallo** [comment]
Hey, thanks for the quick reply.

As far as I know, you always need to use the --plugin=contrib/plugins, they are not included automatically (source: [Specifying Additional Plugin Directories](https://github.com/volatilityfoundation/volatility/wiki/Volatility%20Usage#specifying-additional-plugin-directories))

In that case, I thought it was easier to put all the plugins in the simpler path (`/plugins`), as it's easier for users to add their own plugins and browse inside the container. Adding `--plugins=/usr/lib/python2.7/site-packages/volatility-2.6-py2.7.egg/contrib/plugins` is a lot uglier :-)

What we can do is add the `--plugins=/plugins` to the default container entrypoint.

**Comment by blacktop** [comment]
You are correct about loading addition plugins not being the default, however, because I put them in the `contrib` folder according to that link you posted you should only have to link to `--plugin=contrib/plugins` which is why I did it, but I can't tell if it is actually loading them or not?    I like using the `/plugins` folder better too, however.  Thank you!

**Comment by morallo** [comment]
According to my tests, it doesn't work unless you specify the absolute path

**Pull request merged**
